"""
export.py — Génère un document Word (.docx) ou PDF à partir d'une analyse,
pour que l'avocat puisse l'imprimer, l'annoter ou l'intégrer à son dossier.
"""

import re
from datetime import datetime
from pathlib import Path
import paths
import analyse as legacy_analyse

EXPORTS_DIR = paths.base_dir() / "exports"

# --- Balisage des références juridiques (voir analyse.REGLE_BALISAGE_CITATIONS) --
# Un .docx/.pdf est une page statique, contrairement au front (RichOutput.tsx)
# qui interprète la balise brute [ART:...]/[JURISPRUDENCE:...]/[VERIF:...]
# pour un rendu visuel dédié -- ici, on la convertit une fois en texte
# lisible avant toute insertion dans le document, plutôt que de laisser la
# syntaxe brute apparaître telle quelle sur une page imprimée.
_CODES_LIBELLES_EXPORT = {
    "CP": "Code pénal", "CCIV": "Code civil", "CPC": "Code de procédure civile",
    "CPP": "Code de procédure pénale", "CTRAV": "Code du travail", "CCOM": "Code de commerce",
}
_RE_TAG_ART_EXPORT = re.compile(r"\[ART:([^:\]]+):([A-Z]+)\]")
_RE_TAG_JURISPRUDENCE_EXPORT = re.compile(r"\[JURISPRUDENCE:([^\]]+)\]")
_RE_TAG_VERIF_EXPORT = re.compile(r"\[VERIF:([^\]]*)\]")


def _rendre_balises_lisibles(texte: str) -> str:
    """Convertit les balises en texte lisible pour un document imprimé --
    [ART:132-24:CP] -> "art. 132-24 du Code pénal", [JURISPRUDENCE:...] ->
    la référence seule, [VERIF:...] -> "[À VÉRIFIER : ...]" (reprend
    l'ancien marqueur en texte libre, qui reste immédiatement reconnaissable
    à l'impression, contrairement à la syntaxe de la balise elle-même)."""
    if not texte:
        return texte
    texte = _RE_TAG_ART_EXPORT.sub(
        lambda m: f"art. {m.group(1)} du {_CODES_LIBELLES_EXPORT.get(m.group(2), m.group(2))}", texte
    )
    texte = _RE_TAG_JURISPRUDENCE_EXPORT.sub(lambda m: m.group(1), texte)
    texte = _RE_TAG_VERIF_EXPORT.sub(lambda m: f"[À VÉRIFIER : {m.group(1)}]", texte)
    return texte


def _nettoyer_balises(valeur):
    """Applique _rendre_balises_lisibles récursivement à toute structure
    (dict/list/str) -- appelée une fois en tête de chaque fonction
    d'export, plutôt que sur chaque site d'insertion individuel dans le
    document (arguments, plan, notes...), pour ne pas avoir à en oublier
    un au milieu des dizaines d'appels add_run()/Paragraph() de ce module."""
    if isinstance(valeur, str):
        return _rendre_balises_lisibles(valeur)
    if isinstance(valeur, list):
        return [_nettoyer_balises(v) for v in valeur]
    if isinstance(valeur, dict):
        return {k: _nettoyer_balises(v) for k, v in valeur.items()}
    return valeur

# --- Titres et en-têtes bilingues (internationalisation FR/EN) -------------
# La langue vient du même ContextVar que analyse._directive_langue() (posé
# par le middleware X-Langue, voir backend/app/main.py) -- pas de paramètre
# supplémentaire à ajouter aux fonctions d'export ni à leurs appelants.
# Le contenu généré par l'IA (arguments, plan, objections...) est déjà dans
# la bonne langue en amont ; seuls les titres/en-têtes de mise en forme
# ajoutés ici par export.py doivent être traduits explicitement.
_LIBELLES_EXPORT = {
    "analyse_titre": {"fr": "Analyse", "en": "Analysis"},
    "domaine": {"fr": "Domaine", "en": "Area of law"},
    "non_precise": {"fr": "non précisé", "en": "not specified"},
    "genere_le": {"fr": "Généré le", "en": "Generated on"},
    "niveau_risque": {"fr": "Niveau de risque", "en": "Risk level"},
    "points_attention": {"fr": "Points d'attention", "en": "Points of attention"},
    "footer_analyse": {
        "fr": "Document généré par un outil d'assistance IA. Toute référence marquée \"À VÉRIFIER\" doit être contrôlée avant utilisation en plaidoirie.",
        "en": "Document generated by an AI assistance tool. Any reference flagged \"TO VERIFY\" must be checked before use in pleadings.",
    },
    "dossier_complet_titre": {"fr": "Dossier complet", "en": "Complete case file"},
    "plan_titre": {"fr": "Plan de plaidoirie", "en": "Pleading plan"},
    "points_attention_plan": {"fr": "Points d'attention (plan)", "en": "Points of attention (plan)"},
    "analyse_arguments_adverses_titre": {"fr": "Analyse des arguments adverses", "en": "Analysis of the opposing arguments"},
    "points_attention_analyse": {"fr": "Points d'attention (analyse)", "en": "Points of attention (analysis)"},
    "questions_objections_titre": {"fr": "Questions et objections probables", "en": "Likely questions and objections"},
    "point_plus_faible_titre": {"fr": "Point le plus faible du dossier", "en": "Weakest point of the case"},
    "point_sur_dossier_titre": {"fr": "Point sur votre dossier", "en": "Update on your case"},
    "prepare_le": {"fr": "Préparé le", "en": "Prepared on"},
    "footer_note_client": {
        "fr": "Ce document est une synthèse simplifiée destinée à votre information. N'hésitez pas à contacter votre avocat pour toute question.",
        "en": "This document is a simplified summary for your information. Feel free to contact your lawyer with any questions.",
    },
    "faits_dossier_titre": {"fr": "Faits du dossier", "en": "Case facts"},
    "numero_reference": {"fr": "Numéro de référence", "en": "Reference number"},
    "parties": {"fr": "Parties", "en": "Parties"},
    "exporte_le": {"fr": "Exporté le", "en": "Exported on"},
    "aucun_fait": {"fr": "Aucun fait enregistré pour ce dossier.", "en": "No facts recorded for this case."},
    "footer_faits_bruts": {
        "fr": "Export brut des faits saisis dans l'outil — aucune analyse ni reformulation IA.",
        "en": "Raw export of the facts entered in the tool — no AI analysis or rewriting.",
    },
    "plaidia_signature": {"fr": "Plaid'IA — assistant de préparation de plaidoirie", "en": "Plaid'IA — pleading preparation assistant"},
    "chronologie_titre": {"fr": "Chronologie", "en": "Timeline"},
    "date": {"fr": "Date", "en": "Date"},
    "evenement": {"fr": "Événement", "en": "Event"},
}


def _l(cle: str) -> str:
    entree = _LIBELLES_EXPORT.get(cle, {})
    return entree.get(legacy_analyse.langue_requete(), entree.get("fr", cle))

# Page de garde : reproduction statique (PNG) du motif d'arche gothique de
# frontend/src/components/GothicMotif.tsx -- ce composant est du React/SVG,
# inutilisable tel quel dans un document Word/PDF généré côté Python, d'où
# cet asset généré une fois (voir assets/page_de_garde_motif.png) plutôt
# qu'un rendu à la volée. Absent = page de garde sans image, jamais une
# erreur (voir _ajouter_page_de_garde_word / _page_de_garde_pdf_flowables).
PAGE_DE_GARDE_MOTIF = paths.base_dir() / "assets" / "page_de_garde_motif.png"

RISK_ORDER = {"Élevé": 0, "Moyen": 1, "Faible": 2}


def _nom_fichier(dossier_nom: str, extension: str) -> str:
    safe_nom = "".join(c if c.isalnum() or c in " -_" else "_" for c in dossier_nom).strip()
    date_str = datetime.now().strftime("%Y-%m-%d_%Hh%M")
    return f"{safe_nom}_{date_str}.{extension}"


def _ajouter_page_de_garde_word(doc, titre: str, sous_titre: str = "") -> None:
    """Insère une page de garde (motif, titre, sous-titre, date) avant le
    contenu du document, puis un saut de page. Partagée par toutes les
    fonctions d'export Word ci-dessous."""
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    for _ in range(3):
        doc.add_paragraph()

    if PAGE_DE_GARDE_MOTIF.exists():
        p_image = doc.add_paragraph()
        p_image.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p_image.add_run().add_picture(str(PAGE_DE_GARDE_MOTIF), width=Inches(2.1))

    p_titre = doc.add_paragraph()
    p_titre.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_titre = p_titre.add_run(titre)
    run_titre.bold = True
    run_titre.font.size = Pt(20)

    if sous_titre:
        p_sous = doc.add_paragraph()
        p_sous.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run_sous = p_sous.add_run(sous_titre)
        run_sous.italic = True
        run_sous.font.size = Pt(12)

    p_date = doc.add_paragraph()
    p_date.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_date.add_run(f"{_l('genere_le')} {datetime.now().strftime('%d/%m/%Y à %H:%M')}").italic = True
    p_date.runs[0].font.size = Pt(9)

    p_marque = doc.add_paragraph()
    p_marque.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_marque.add_run(_l("plaidia_signature")).font.size = Pt(9)

    doc.add_page_break()


def _page_de_garde_pdf_flowables(titre: str, sous_titre: str = "") -> list:
    """Équivalent PDF de _ajouter_page_de_garde_word : une liste de
    flowables reportlab à préfixer à la 'story' de chaque export PDF."""
    from reportlab.platypus import Image, Paragraph, PageBreak, Spacer
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib.colors import HexColor
    from reportlab.lib.enums import TA_CENTER

    styles = getSampleStyleSheet()
    titre_style = ParagraphStyle("PageGardeTitre", parent=styles["Title"], alignment=TA_CENTER, fontSize=20, spaceAfter=6)
    sous_style = ParagraphStyle("PageGardeSousTitre", parent=styles["Normal"], alignment=TA_CENTER, fontName="Helvetica-Oblique", fontSize=12)
    date_style = ParagraphStyle("PageGardeDate", parent=styles["Normal"], alignment=TA_CENTER, fontName="Helvetica-Oblique", fontSize=9, textColor=HexColor("#666666"))

    flowables = [Spacer(1, 3.5 * cm)]
    if PAGE_DE_GARDE_MOTIF.exists():
        img = Image(str(PAGE_DE_GARDE_MOTIF), width=3.5 * cm, height=5.25 * cm)
        img.hAlign = "CENTER"
        flowables += [img, Spacer(1, 1 * cm)]
    flowables.append(Paragraph(titre, titre_style))
    if sous_titre:
        flowables.append(Paragraph(sous_titre, sous_style))
    flowables += [
        Spacer(1, 0.6 * cm),
        Paragraph(f"{_l('genere_le')} {datetime.now().strftime('%d/%m/%Y à %H:%M')}", date_style),
        Paragraph(_l("plaidia_signature"), date_style),
        PageBreak(),
    ]
    return flowables


def exporter_word(dossier: dict, result: dict) -> str:
    """Génère un .docx et retourne le chemin du fichier créé."""
    dossier = dict(dossier)
    result = _nettoyer_balises(result)
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise ImportError("python-docx n'est pas installé. Lancez : pip install python-docx")

    EXPORTS_DIR.mkdir(exist_ok=True)

    doc = Document()
    _ajouter_page_de_garde_word(doc, f"{_l('analyse_titre')} — {dossier['nom']}", dossier.get("domaine") or "")

    title = doc.add_heading(f"{_l('analyse_titre')} — {dossier['nom']}", level=1)

    meta = doc.add_paragraph()
    meta.add_run(f"{_l('domaine')} : {dossier.get('domaine') or _l('non_precise')}\n").italic = True
    meta.add_run(f"{_l('genere_le')} : {datetime.now().strftime('%d/%m/%Y à %H:%M')}").italic = True

    doc.add_paragraph()

    args_sorted = sorted(
        result.get("arguments", []), key=lambda a: RISK_ORDER.get(a.get("risque", "Moyen"), 1)
    )

    for i, arg in enumerate(args_sorted, 1):
        h = doc.add_heading(f"{i}. {arg.get('resume', '')}", level=2)

        risk_p = doc.add_paragraph()
        risk_run = risk_p.add_run(f"{_l('niveau_risque')} : {arg.get('risque', '?')}")
        risk_run.bold = True
        if arg.get("risque") == "Élevé":
            risk_run.font.color.rgb = RGBColor(0xC0, 0x30, 0x30)
        elif arg.get("risque") == "Moyen":
            risk_run.font.color.rgb = RGBColor(0xB0, 0x80, 0x00)
        else:
            risk_run.font.color.rgb = RGBColor(0x30, 0x80, 0x40)

        doc.add_paragraph(f"Fondement : {arg.get('fondement', '')}")
        raisonnement = arg.get("raisonnement") or {}
        if raisonnement.get("probleme_de_droit"):
            doc.add_paragraph(f"Problème de droit : {raisonnement.get('probleme_de_droit', '')}")
        if raisonnement.get("regle_applicable"):
            doc.add_paragraph(f"Règle applicable : {raisonnement.get('regle_applicable', '')}")
        if raisonnement.get("application_aux_faits"):
            doc.add_paragraph(f"Application aux faits : {raisonnement.get('application_aux_faits', '')}")
        doc.add_paragraph(f"Justification : {arg.get('justification_risque', '')}")

        if arg.get("refutations"):
            doc.add_paragraph("Pistes de réfutation :", style="Intense Quote")
            for r in arg["refutations"]:
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(f"[{r.get('angle', '')}] ").bold = True
                p.add_run(r.get("piste", ""))

        doc.add_paragraph()

    if result.get("points_attention"):
        doc.add_heading(_l("points_attention"), level=2)
        for point in result["points_attention"]:
            doc.add_paragraph(point, style="List Bullet")

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        _l("footer_analyse")
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    filename = _nom_fichier(dossier["nom"], "docx")
    path = EXPORTS_DIR / filename
    doc.save(str(path))
    return str(path)


def exporter_pdf(dossier: dict, result: dict) -> str:
    """Génère un .pdf et retourne le chemin du fichier créé."""
    dossier = dict(dossier)
    result = _nettoyer_balises(result)
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import cm
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    except ImportError:
        raise ImportError("reportlab n'est pas installé. Lancez : pip install reportlab")

    EXPORTS_DIR.mkdir(exist_ok=True)

    filename = _nom_fichier(dossier["nom"], "pdf")
    path = EXPORTS_DIR / filename

    doc = SimpleDocTemplate(str(path), pagesize=A4,
                             leftMargin=2*cm, rightMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitrePerso", parent=styles["Heading1"], fontSize=16, spaceAfter=12)
    h2_style = ParagraphStyle("H2Perso", parent=styles["Heading2"], fontSize=12, spaceBefore=14, spaceAfter=6)
    normal = styles["Normal"]
    italic = ParagraphStyle("ItalicPerso", parent=normal, fontName="Helvetica-Oblique", fontSize=9, textColor=HexColor("#555555"))

    risk_colors = {"Élevé": "#C03030", "Moyen": "#B08000", "Faible": "#308040"}

    story = _page_de_garde_pdf_flowables(f"{_l('analyse_titre')} — {dossier['nom']}", dossier.get("domaine") or "")
    story.append(Paragraph(f"{_l('analyse_titre')} — {dossier['nom']}", title_style))
    story.append(Paragraph(f"{_l('domaine')} : {dossier.get('domaine') or _l('non_precise')}", italic))
    story.append(Paragraph(f"{_l('genere_le')} : {datetime.now().strftime('%d/%m/%Y à %H:%M')}", italic))
    story.append(Spacer(1, 0.5*cm))

    args_sorted = sorted(
        result.get("arguments", []), key=lambda a: RISK_ORDER.get(a.get("risque", "Moyen"), 1)
    )

    for i, arg in enumerate(args_sorted, 1):
        story.append(Paragraph(f"{i}. {arg.get('resume', '')}", h2_style))
        risque = arg.get("risque", "?")
        color = risk_colors.get(risque, "#333333")
        story.append(Paragraph(f'<font color="{color}"><b>{_l("niveau_risque")} : {risque}</b></font>', normal))
        story.append(Paragraph(f"<b>Fondement :</b> {arg.get('fondement', '')}", normal))
        raisonnement = arg.get("raisonnement") or {}
        if raisonnement.get("probleme_de_droit"):
            story.append(Paragraph(f"<b>Problème de droit :</b> {raisonnement.get('probleme_de_droit', '')}", normal))
        if raisonnement.get("regle_applicable"):
            story.append(Paragraph(f"<b>Règle applicable :</b> {raisonnement.get('regle_applicable', '')}", normal))
        if raisonnement.get("application_aux_faits"):
            story.append(Paragraph(f"<b>Application aux faits :</b> {raisonnement.get('application_aux_faits', '')}", normal))
        story.append(Paragraph(f"<b>Justification :</b> {arg.get('justification_risque', '')}", normal))

        if arg.get("refutations"):
            items = []
            for r in arg["refutations"]:
                items.append(ListItem(Paragraph(f"<b>[{r.get('angle', '')}]</b> {r.get('piste', '')}", normal)))
            story.append(Spacer(1, 0.2*cm))
            story.append(ListFlowable(items, bulletType="bullet"))

        story.append(Spacer(1, 0.4*cm))

    if result.get("points_attention"):
        story.append(Paragraph(_l("points_attention"), h2_style))
        items = [ListItem(Paragraph(p, normal)) for p in result["points_attention"]]
        story.append(ListFlowable(items, bulletType="bullet"))

    story.append(Spacer(1, 0.6*cm))
    story.append(Paragraph(
        _l("footer_analyse"),
        italic
    ))

    doc.build(story)
    return str(path)


def exporter_dossier_complet_word(dossier: dict, analyse: dict | None, plan: dict | None, simulateur: dict | None) -> str:
    """Génère un .docx unique combinant analyse, plan de plaidoirie et
    simulateur d'objections pour un dossier — le rapport complet à emporter
    à l'audience. Chaque section est optionnelle."""
    dossier = dict(dossier)
    analyse = _nettoyer_balises(analyse)
    plan = _nettoyer_balises(plan)
    simulateur = _nettoyer_balises(simulateur)
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
    except ImportError:
        raise ImportError("python-docx n'est pas installé. Lancez : pip install python-docx")

    EXPORTS_DIR.mkdir(exist_ok=True)
    doc = Document()
    _ajouter_page_de_garde_word(doc, f"{_l('dossier_complet_titre')} — {dossier['nom']}", dossier.get("domaine") or "")

    doc.add_heading(f"{_l('dossier_complet_titre')} — {dossier['nom']}", level=1)
    meta = doc.add_paragraph()
    meta.add_run(f"{_l('domaine')} : {dossier.get('domaine') or _l('non_precise')}\n").italic = True
    meta.add_run(f"{_l('genere_le')} : {datetime.now().strftime('%d/%m/%Y à %H:%M')}").italic = True
    doc.add_paragraph()

    if plan:
        doc.add_heading(f"1. {_l('plan_titre')}", level=1)
        doc.add_paragraph("Accroche", style="Intense Quote")
        doc.add_paragraph(plan.get("accroche", ""))
        for i, point in enumerate(plan.get("plan", []), 1):
            doc.add_heading(f"{i}. {point.get('point', '')} ({point.get('duree_minutes', '?')} min)", level=2)
            doc.add_paragraph(f"Argument clé : {point.get('argument_cle', '')}")
            doc.add_paragraph(f"Notes : {point.get('notes', '')}")
        doc.add_paragraph("Conclusion", style="Intense Quote")
        doc.add_paragraph(plan.get("conclusion", ""))
        if plan.get("points_attention"):
            doc.add_heading(_l("points_attention_plan"), level=2)
            for p in plan["points_attention"]:
                doc.add_paragraph(p, style="List Bullet")
        doc.add_paragraph()

    if analyse:
        doc.add_heading(f"2. {_l('analyse_arguments_adverses_titre')}", level=1)
        args_sorted = sorted(analyse.get("arguments", []), key=lambda a: RISK_ORDER.get(a.get("risque", "Moyen"), 1))
        for i, arg in enumerate(args_sorted, 1):
            h = doc.add_heading(f"{i}. {arg.get('resume', '')}", level=2)
            risk_p = doc.add_paragraph()
            risk_run = risk_p.add_run(f"{_l('niveau_risque')} : {arg.get('risque', '?')}")
            risk_run.bold = True
            doc.add_paragraph(f"Fondement : {arg.get('fondement', '')}")
            raisonnement = arg.get("raisonnement") or {}
            if raisonnement.get("probleme_de_droit"):
                doc.add_paragraph(f"Problème de droit : {raisonnement.get('probleme_de_droit', '')}")
            if raisonnement.get("regle_applicable"):
                doc.add_paragraph(f"Règle applicable : {raisonnement.get('regle_applicable', '')}")
            if raisonnement.get("application_aux_faits"):
                doc.add_paragraph(f"Application aux faits : {raisonnement.get('application_aux_faits', '')}")
            if arg.get("justification_risque"):
                doc.add_paragraph(f"Justification : {arg.get('justification_risque', '')}")
            if arg.get("refutations"):
                doc.add_paragraph("Pistes de réfutation :", style="Intense Quote")
                for r in arg["refutations"]:
                    p = doc.add_paragraph(style="List Bullet")
                    p.add_run(f"[{r.get('angle', '')}] ").bold = True
                    p.add_run(r.get("piste", ""))
        if analyse.get("points_attention"):
            doc.add_heading(_l("points_attention_analyse"), level=2)
            for p in analyse["points_attention"]:
                doc.add_paragraph(p, style="List Bullet")
        doc.add_paragraph()

    if simulateur:
        doc.add_heading(f"3. {_l('questions_objections_titre')}", level=1)
        for i, obj in enumerate(simulateur.get("objections", []), 1):
            doc.add_heading(f"{i}. [{obj.get('origine', '?')}] {obj.get('question', '')}", level=2)
            doc.add_paragraph(f"Piège : {obj.get('piege', '')}")
            doc.add_paragraph(f"Piste de réponse : {obj.get('piste_reponse', '')}")
        if simulateur.get("point_le_plus_faible"):
            doc.add_heading(_l("point_plus_faible_titre"), level=2)
            doc.add_paragraph(simulateur["point_le_plus_faible"])
        doc.add_paragraph()

    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        _l("footer_analyse")
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    filename = _nom_fichier(f"{dossier['nom']}_complet", "docx")
    path = EXPORTS_DIR / filename
    doc.save(str(path))
    return str(path)


def exporter_note_client_word(dossier: dict, texte_note: str) -> str:
    """Génère un .docx contenant la note explicative destinée au client,
    en langage simple — prête à être envoyée telle quelle."""
    dossier = dict(dossier)
    texte_note = _rendre_balises_lisibles(texte_note)
    try:
        from docx import Document
        from docx.shared import Pt
    except ImportError:
        raise ImportError("python-docx n'est pas installé. Lancez : pip install python-docx")

    EXPORTS_DIR.mkdir(exist_ok=True)
    doc = Document()
    _ajouter_page_de_garde_word(doc, f"{_l('point_sur_dossier_titre')} — {dossier['nom']}")

    doc.add_heading(f"{_l('point_sur_dossier_titre')} — {dossier['nom']}", level=1)
    meta = doc.add_paragraph()
    meta.add_run(f"{_l('prepare_le')} {datetime.now().strftime('%d/%m/%Y')}").italic = True
    doc.add_paragraph()

    for paragraphe in texte_note.split("\n\n"):
        if paragraphe.strip():
            doc.add_paragraph(paragraphe.strip())

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        _l("footer_note_client")
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    filename = _nom_fichier(f"{dossier['nom']}_note_client", "docx")
    path = EXPORTS_DIR / filename
    doc.save(str(path))
    return str(path)


def exporter_faits_bruts_word(dossier: dict) -> str:
    """Exporte les faits bruts d'un dossier (tels qu'accumulés via
    'Préparer mon dossier' ou saisis à la création), sans analyse ni
    reformulation — pour classer avec le dossier physique du client."""
    dossier = dict(dossier)
    try:
        from docx import Document
        from docx.shared import Pt
    except ImportError:
        raise ImportError("python-docx n'est pas installé. Lancez : pip install python-docx")

    EXPORTS_DIR.mkdir(exist_ok=True)
    doc = Document()
    _ajouter_page_de_garde_word(doc, f"{_l('faits_dossier_titre')} — {dossier['nom']}", dossier.get("domaine") or "")

    doc.add_heading(f"{_l('faits_dossier_titre')} — {dossier['nom']}", level=1)
    meta = doc.add_paragraph()
    meta.add_run(f"{_l('domaine')} : {dossier.get('domaine') or _l('non_precise')}\n").italic = True
    if dossier.get("numero_dossier"):
        meta.add_run(f"{_l('numero_reference')} : {dossier['numero_dossier']}\n").italic = True
    if dossier.get("parties"):
        meta.add_run(f"{_l('parties')} : {dossier['parties']}\n").italic = True
    meta.add_run(f"{_l('exporte_le')} : {datetime.now().strftime('%d/%m/%Y à %H:%M')}").italic = True
    doc.add_paragraph()

    faits = dossier.get("faits") or ""
    if not faits.strip():
        doc.add_paragraph(_l("aucun_fait"))
    else:
        for ligne in faits.split("\n"):
            if ligne.strip():
                doc.add_paragraph(ligne.strip())
            else:
                doc.add_paragraph()

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        _l("footer_faits_bruts")
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)

    filename = _nom_fichier(f"{dossier['nom']}_faits_bruts", "docx")
    path = EXPORTS_DIR / filename
    doc.save(str(path))
    return str(path)


def exporter_texte_libre_word(titre: str, texte: str, note_bas_page: str = "") -> str:
    """Export générique d'un texte libre en Word, sans nécessiter de
    dossier en base — utilisé notamment pour les procès-verbaux, qui
    peuvent être rédigés avant même la création d'une affaire dans l'outil."""
    texte = _rendre_balises_lisibles(texte)
    try:
        from docx import Document
        from docx.shared import Pt
    except ImportError:
        raise ImportError("python-docx n'est pas installé. Lancez : pip install python-docx")

    EXPORTS_DIR.mkdir(exist_ok=True)
    doc = Document()
    _ajouter_page_de_garde_word(doc, titre)

    doc.add_heading(titre, level=1)
    meta = doc.add_paragraph()
    meta.add_run(f"{_l('genere_le')} {datetime.now().strftime('%d/%m/%Y à %H:%M')}").italic = True
    doc.add_paragraph()

    for ligne in texte.split("\n"):
        if ligne.strip():
            doc.add_paragraph(ligne.strip())
        else:
            doc.add_paragraph()

    if note_bas_page:
        doc.add_paragraph()
        footer = doc.add_paragraph()
        footer_run = footer.add_run(note_bas_page)
        footer_run.italic = True
        footer_run.font.size = Pt(9)

    filename = _nom_fichier(titre, "docx")
    path = EXPORTS_DIR / filename
    doc.save(str(path))
    return str(path)


def exporter_csv(titre: str, en_tetes: list[str], lignes: list[list[str]]) -> str:
    """Export générique d'un tableau en CSV — pour les résultats
    naturellement tabulaires (ex. chronologie) où un tableur est plus
    approprié qu'un document Word (voir AUDIT_IMPORT_EXPORT.md §6).
    UTF-8 avec BOM (utf-8-sig) pour qu'Excel affiche correctement les
    accents à l'ouverture directe du fichier, sans réglage manuel."""
    import csv

    lignes = _nettoyer_balises(lignes)
    EXPORTS_DIR.mkdir(exist_ok=True)
    filename = _nom_fichier(titre, "csv")
    path = EXPORTS_DIR / filename
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(en_tetes)
        writer.writerows(lignes)
    return str(path)
